import crypto from "crypto";

export function generateAccessToken(email: string):string{
    const randToken = crypto.randomBytes(20).toString('hex');
    return Buffer.from(email).toString('base64')  + '.' + Buffer.from(randToken).toString('base64');
}

export function encryptPassword(password: string){
    return crypto.createHash('sha256').update(password).digest('hex');
}

/**
 * @param access_token - An access token of the form generated by the generate access token function
 * @return The user's email
 */
export function decodeAccessToken(access_token: string):string{
    const [encodedEmail, token] = access_token.split('.');
    return Buffer.from(encodedEmail, 'base64').toString();
}
